version: "3.12"
services:
  satellite:
    build: .
    volumes: 
      - .:/django
    ports:
      - 8000:8000
    image: satellite:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000